version: '3'

services:
  app:
    image: node:20.12.0
    container_name: zain-admin
    working_dir: /zain-admin-ui
    volumes:
      - .:/admin
    ports:
      - "3001:3001"
    depends_on:
      - db
      - elasticsearch
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Root@12
      - MYSQL_DB=flone2
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    command: sh -c "npm install && npm start"
      
  db:
    image: mysql:8.0
    container_name: zain-db
    environment:
      MYSQL_ROOT_PASSWORD: Root@12
      MYSQL_DATABASE: flone2
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@12
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: zain-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  db_data:
  es_data:
