# Generated by Django 5.0.4 on 2024-05-27 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_phone_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='12345678910', max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits only', regex='^\\d{11}')]),
        ),
    ]
