# Generated by Django 5.0.4 on 2024-05-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_max_otp_out_user_max_otp_try_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=4),
        ),
    ]
