# Generated by Django 5.0.4 on 2024-05-28 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits only', regex='^\\d{13}')]),
        ),
    ]
