# Generated by Django 5.0.4 on 2024-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
