# Generated by Django 5.0.4 on 2024-04-19 06:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/default.jpg', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
