# Generated by Django 5.0.4 on 2024-04-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='useremail',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
