# Use the Node.js image with version 20.12.0
FROM node:20.12.0

# Set the working directory inside the container
WORKDIR /admin

# Copy all the files from the local directory to the working directory in the container
COPY . .

# Install all dependencies listed in package.json
RUN npm install

# Expose port 3000
EXPOSE 3001

# Command to run the application
CMD ["npm", "start"]
