FROM node:21.7.1

# Set the working directory
WORKDIR /app

# Copy all files from the current directory to the container
COPY . .

# Install dependencies using npm
RUN npm install

# Expose the port your app runs on
EXPOSE 3000

# Command to run your app
CMD ["npm", "start"]
