# Generated by Django 5.0.4 on 2024-07-03 11:06

import commerce.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(default='default.jpg', upload_to=commerce.models.upload_to, verbose_name='Image')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('salesCount', models.IntegerField()),
                ('short_description', models.TextField(max_length=500)),
                ('stock', models.IntegerField(default=1)),
                ('price_id', models.CharField(default='', max_length=250)),
                ('price_id_eur', models.CharField(default='', max_length=250)),
                ('price_id_gbp', models.CharField(default='', max_length=250)),
                ('Category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('tag', models.ManyToManyField(to='blog.tag')),
            ],
            options={
                'db_table': 'commerce_product',
            },
        ),
    ]
